const JOIN_EMAIL_CHANGE = "JOIN_EMAIL_CHANGE"
const JOIN_PASSWORD_CHANGE = "JOIN_PASSWORD_CHANGE"
const JOIN_EMPTY_EMAIL = "JOIN_EMPTY_EMAIL"
const JOIN_EMPTY_PASSWORD = "JOIN_EMPTY_PASSWORD"
const JOIN_INVALID_EMAIL = "JOIN_INVALID_EMAIL"
const JOIN_INVALID_PASSWORD = "JOIN_INVALID_PASSWORD"
const JOIN_NOT_AVAILABLE_EMAIL = "JOIN_NOT_AVAILABLE_EMAIL"

export {
  JOIN_EMAIL_CHANGE,
  JOIN_PASSWORD_CHANGE,
  JOIN_EMPTY_EMAIL,
  JOIN_EMPTY_PASSWORD,
  JOIN_INVALID_EMAIL,
  JOIN_INVALID_PASSWORD,
  JOIN_NOT_AVAILABLE_EMAIL
}