const GOOGLE_AUTH_STATE = "GOOGLE_AUTH_STATE"
const USERNAME_STATE = "USERNAME_STATE"
const USER_STATE = "USER_STATE"
const USERNAME_CHANGE = "USERNAME_CHANGE"

export {
  GOOGLE_AUTH_STATE,
  USERNAME_STATE,
  USER_STATE,
  USERNAME_CHANGE
}