export const SIGNUP_UPDATE_USERNAME = "SIGNUP_UPDATE_USERNAME"
export const SIGNUP_EMPTY_USERNAME = "SIGNUP_EMPTY_USERNAME"
export const SIGNUP_INVALID_USERNAME = "SIGNUP_INVALID_USERNAME"
export const SIGNUP_REQUIRED_USERNAME = "SIGNUP_REQUIRED_USERNAME"