const SIGNIN_USERNAME_INPUT = "SIGNIN_USERNAME_INPUT"
const SIGNIN_EMAIL_INPUT = "SIGNIN_EMAIL_INPUT"
const SIGNIN_PASSWORD_INPUT = "SIGNIN_PASSWORD_INPUT"

export {
  SIGNIN_USERNAME_INPUT,
  SIGNIN_EMAIL_INPUT,
  SIGNIN_PASSWORD_INPUT
}